---

- name: ensure filebeat presence
  package:
    name: filebeat
    state: present
  tags: install

- name: establish filebeat configuration
  when: filebeat_configuration is defined and filebeat_configuration
  template:
    src: filebeat.yml.j2
    dest: "{{ filebeat_config_path }}/filebeat.yml"
  notify: restart filebeat
  tags: configure

- name: establish filebeat systemd configuration
  systemd:
    name: filebeat
    enabled: true
    state: started
  tags: configure
