---

- name: ensure filebeat presence
  package:
    name: filebeat
    state: present
  tags: install

- name: establish filebeat configuration 
  template:
    src: filebeat.yml.j2
    dest: "{{ config_path }}/filebeat.yml"
  tags: configure

- name: establish filebeat systemd configuration
  systemd:
    name: filebeat
    enabled: "{{ filebeat['enabled'] }}" 
    state: "{{ filebeat['state'] }}"
  tags: configure
